# Generated by Django 2.2.6 on 2025-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerledger_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='karigar',
            field=models.BooleanField(default=False),
        ),
    ]
