# Generated by Django 2.2.6 on 2025-05-08 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_karigar'),
        ('product', '0010_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarigarProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('decription', models.CharField(blank=True, max_length=400, null=True)),
                ('karigar_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('karigar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_karigar', to='customer.Customer')),
            ],
        ),
    ]
