# Generated by Django 2.2.6 on 2025-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
