# Generated by Django 2.2.6 on 2025-12-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplierstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstatement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='supplier.Supplier'),
        ),
    ]
